### ISSUE TITLE
Test measurement data

### ISSUE THREAD

**Issue by oherrala** [vk6flab/rhp#1]
Please consider publishing test measurement data. This would allow verification of your findings and further analysis as well as comparing your results to other results.

**Comment by vk6flab** [comment]
Thank you for the suggestion to publish the raw data. Prior to releasing the report we discussed this extensively and made the decision to leave the measurements unpublished for the following reasons:

* We did not seek or gain permission to publish the raw data.
* We cannot guarantee anonymity because some radios are unique in the dataset.
* The test equipment was not calibrated and while we're confident with our methodologies, in our opinion, raw data without context has the potential for misrepresentation.
